sudo: required
services:
  - docker
before_install:
- docker build -t keerthana814/docker-react -f Dockerfile.dev .

script:
- docker run -e CI=true keerthana814/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  # search in S3 bucket
  bucket_name: "elasticbeanstalk-us-west-2-373372700828" 
  # 1st time the app name
  bucket_path: "docker-react"
  # specifies that only when master gets new code deploy it
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
