sudo: required
services:
  - docker
before_install:
- docker build -t keerthana814/docker-react -f Dockerfile .

script:
- docker run -e CI=true keerthana814/docker-react npm run test

# Docker-env.eba-pcgrkbdb.ap-south-1.elasticbeanstalk.com 
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  # search in S3 bucket
  bucket_name: "elasticbeanstalk-ap-south-1-373372700828" 
  # 1st time the app name
  bucket_path: "docker"
  # specifies that only when master gets new code deploy it
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
